# Generated by Django 4.0.1 on 2022-01-31 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='sharer_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 5, 33, 46, 938824, tzinfo=utc)),
        ),
    ]
