# Generated by Django 4.0.6 on 2022-07-31 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 0, 44, 9, 716775, tzinfo=utc)),
        ),
    ]
