# Generated by Django 4.1 on 2022-08-10 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 9, 59, 2, 194062, tzinfo=datetime.timezone.utc)),
        ),
    ]
