# Generated by Django 4.1 on 2022-08-12 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_ride_arrivaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivaltime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 3, 11, 32, 172037, tzinfo=datetime.timezone.utc)),
        ),
    ]
